-- 코드를 입력하세요
SELECT YEAR(o.SALES_DATE) AS YEAR
      ,MONTH(o.SALES_DATE) AS MONTH
      ,u.GENDER
      ,COUNT(DISTINCT o.USER_ID) AS USERS
FROM USER_INFO u
    INNER JOIN ONLINE_SALE o ON u.user_id = o.user_id
WHERE u.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, u.GENDER
ORDER BY YEAR, MONTH, u.GENDER
