-- 코드를 입력하세요
# SELECT CART_ID 
# FROM CART_PRODUCTS
# GROUP BY CART_ID
# HAVING GROUP_CONCAT(NAME) REGEXP 'Milk'
# AND GROUP_CONCAT(NAME) REGEXP 'Yogurt'
# ORDER BY CART_ID

SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME='MILK' AND CART_ID IN (SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME ="YOGURT") ;