-- 코드를 입력하세요
# SELECT FOOD_TYPE,REST_ID,REST_NAME, FAVORITES
# FROM REST_INFO r1
# WHERE REST_ID IN (
#     SELECT REST_ID
#     FROM 
# )
# ORDER BY FOOD_TYPE DESC

SELECT r2.FOOD_TYPE,r2.REST_ID,r2.REST_NAME, r2.FAVORITES
FROM (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS f1
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) r1 INNER JOIN REST_INFO r2 ON r1.FOOD_TYPE = r2.FOOD_TYPE AND r1.f1 = r2.FAVORITES
ORDER BY r2.FOOD_TYPE DESC

