-- 코드를 입력하세요
-- ins - intact
-- outs - spayed
SELECT i.ANIMAL_ID
      ,i.ANIMAL_TYPE
      ,i.NAME
FROM ANIMAL_INS i
    INNER JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE i.SEX_UPON_INTAKE REGEXP 'Intact'
AND o.SEX_UPON_OUTCOME REGEXP 'Spayed|Neutered'
ORDER BY ANIMAL_ID