-- 코드를 입력하세요
# SELECT HOUR(DATETIME)
# FROM ANIMAL_OUTS

WITH RECURSIVE cnt_hour AS
(SELECT 0 AS n
UNION ALL
SELECT n + 1
FROM cnt_hour
WHERE n < 23
)
SELECT c.n AS HOUR
    , COUNT(HOUR(a.DATETIME)) AS COUNT
FROM ANIMAL_OUTS a
    RIGHT JOIN cnt_hour c ON c.n = HOUR(a.DATETIME)
GROUP BY HOUR
ORDER BY HOUR