-- 코드를 입력하세요
# SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
# FROM (
#     SELECT * 
#     FROM FIRST_HALF f
#     UNION ALL
#     SELECT *
#     FROM JULY
# ) AS a
# GROUP BY FLAVOR
# ORDER BY TOTAL_ORDER DESC
# LIMIT 3

SELECT FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM (
        SELECT * 
        FROM FIRST_HALF f
        UNION ALL
        SELECT *
        FROM JULY
    ) AS a
    GROUP BY FLAVOR
    ORDER BY TOTAL_ORDER DESC
    LIMIT 3
) AS b

