# -- 코드를 입력하세요
WITH ct AS (
    SELECT *
      ,DENSE_RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS rk
    FROM FOOD_PRODUCT
    WHERE CATEGORY REGEXP '과자|국|김치|식용유'
)



SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, PRODUCT_NAME
FROM ct
WHERE rk = 1
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC

