-- 코드를 입력하세요
WITH ct AS (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TOTAL_SALES
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
)

SELECT p.PRODUCT_CODE, TOTAL_SALES*PRICE AS SALES
FROM PRODUCT p
    INNER JOIN ct ON p.PRODUCT_ID = ct.PRODUCT_ID
ORDER BY SALES DESC, p.PRODUCT_CODE