-- 코드를 입력하세요
SELECT o.PRODUCT_ID
      ,p.PRODUCT_NAME
      ,PRICE*SUM(AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT p
    INNER JOIN FOOD_ORDER o ON p.product_id = o.product_id
WHERE o.produce_date BETWEEN '2022-05-01 00:00:00' AND '2022-05-31 23:59:59'
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID