-- 코드를 입력하세요
SELECT r.REST_ID
      ,REST_NAME
      ,FOOD_TYPE
      ,FAVORITES
      ,ADDRESS
      ,ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO i
    INNER JOIN REST_REVIEW r ON i.REST_ID = r.REST_ID
WHERE LEFT(i.ADDRESS,2) = '서울'
GROUP BY r.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC